routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@redirect');

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('listing', 'ListingController');

});

app/Models/Listing.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Listing extends Model
{
    protected $table = 'listing';
    public $timestamps = false;

    public $fillable = [
        'list_name',
        'distance',
        'user_id',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'list_name' => 'string',
        'distance' => 'float',
        'user_id' => 'integer',
    ];

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'user';
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'encrypted_password', 'type',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'encrypted_password',
    ];

    public function getAuthPassword()
    {
        return $this->encrypted_password;
    }

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // protected $casts = [
    //     'email_verified_at' => 'datetime',
    // ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }

    public function redirect()
    {
        return view('welcome');
    }
}

app/Http/Controllers/ListingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Listing;
use App\Models\User;
use Auth;

class ListingController extends Controller
{
    public function index()
    {
        $listings = Listing::with(['user'])->get();

        return view('listing.index')->with('listings', $listings);
    }

    public function create()
    {
        $users = User::all();

        return view('listing.fields')->with('users', $users);
    }

    public function store(Request $request)
    {
        $listing = new Listing;

        $listing->list_name = $request->name;

        $listing->distance = $request->distance;

        // $listing->user_id = $request->user;

        $listing->user_id = Auth::id();

        $listing->save();

        return redirect('/listing');
    }

    public function edit($id)
    {
        $listing = Listing::find($id);

        $users = User::all();

        return view('listing.fields')->with('listing', $listing)
                                     ->with('users', $users);
    }

    public function update($id, Request $request)
    {
        $listing = Listing::find($id);

        $listing->list_name = $request->name;

        $listing->distance = $request->distance;

        // $listing->user_id = $request->user;

        $listing->user_id = Auth::id();

        $listing->save();

        return redirect('/listing');
    }

    public function destroy($id)
    {
        $listing = Listing::find($id);

        $listing->delete();

        return redirect('/listing');
    }

    public function getListing(Request $request)
    {
        $userToken = User::where('token', $request->token)->first();

        if(empty($userToken)) {

            return response()->json(['status' => ['code' => 400, "message" => 'Invalid token']]);
        }

        $user = User::find($request->id);

        if(empty($user)) {

            return response()->json(['status' => ['code' => 400, "message" => 'Invalid User']]);
        }

        $listings = Listing::where('user_id', $user->id)->get()->toJson();

        return response()->json(['listing' => json_decode($listings), 'status' => ['code' => 200, "message" => 'Listing successfully retrieved']]);
    }

    public function updateListing(Request $request)
    {
        $user = User::where('token', $request->token)->first();

        if(empty($user)) {

            return response()->json(['status' => ['code' => 400, "message" => 'Invalid token']]);
        }

        $listing = Listing::find($request->id);

        if(empty($listing)) {

            return response()->json(['status' => ['code' => 400, "message" => 'Invalid listing']]);
        }

        if(!empty($request->list_name)) {

            $listing->list_name = $request->list_name;
        }

        if(!empty($request->distance)) {

            $listing->distance = $request->distance;
        }

        $listing->user_id = $user->id;

        $listing->save();

        return response()->json(['listing' => json_decode($listing->toJson()), 'status' => ['code' => 200, "message" => 'Listing successfully updated']]);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <p>You are logged in!</p>

                    <ul>
                        <li><a href="{{ route('listing.index') }}">Listing</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                                    <a class="dropdown-item" href="{{ route('listing.index') }}">
                                         {{ __('Listing') }}
                                     </a>

                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/listing/fields.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if (!empty($listing))
        {{-- {!! Form::model($listing, ['route' => ['listing.update', $listing->id], 'method' => 'patch']) !!} --}}
        <form action="{{ route('listing.update', $listing->id) }}" method="POST">
            {{ method_field('PATCH') }}
    @else
        <form action="{{ route('listing.store') }}" method="POST">
    @endif
        @csrf
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('List Name') }}</label>

            <div class="col-md-6">
                <input id="name" type="text" class="form-control" name="name" value="{{ $listing->list_name ?? '' }}" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="distance" class="col-md-4 col-form-label text-md-right">{{ __('Distance') }}</label>

            <div class="col-md-6">
                <input id="distance" type="number" step="0.01" class="form-control" name="distance" value="{{ $listing->distance ?? '' }}" required>
            </div>
        </div>

        {{-- <div class="form-group row">
            <label for="user" class="col-md-4 col-form-label text-md-right">{{ __('User') }}</label>

            <div class="col-md-6">
                <select name="user" id="user" class="form-control">
                    @foreach ($users as $user)
                        @if (!empty($listing))
                            @if ($user->id === $listing->user_id)
                                <option value="{{ $user->id }}" selected>{{ $user->email }}</option>
                            @else
                                <option value="{{ $user->id }}">{{ $user->email }}</option>
                            @endif
                        @else
                            <option value="{{ $user->id }}">{{ $user->email }}</option>
                        @endif
                    @endforeach
                </select>
            </div>
        </div> --}}

        <div class="form-group row mb-0">
            <div class="col-md-8 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Submit') }}
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/listing/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <a href="{{ route('listing.create') }}" type="button" class="btn">Add New</a>
    <table class="table table-bordered" style="margin-top:20px;">
        <thead>
            <th>Name</th>
            <th>Distance</th>
            <th>User</th>
            <th>Actions</th>
        </thead>
        <tbody>
            @if (!empty($listings))
                @foreach ($listings as $listing)
                    <tr>
                        <td>{{ $listing->list_name }}</td>
                        <td>{{ $listing->distance }}</td>
                        <td>{{ $listing->user->email }} (ID: {{ $listing->user->id }})</td>
                        <td>
                            <form method="POST" action="{{ route('listing.destroy', $listing->id) }}" accept-charset="UTF-8">
                                {{ method_field('DELETE') }}
                                @csrf
                                <a href="{{ route('listing.edit', $listing->id) }}" class='btn btn-success btn-xs'>Edit</a>
                                <input name="_method" type="hidden" value="DELETE">
                                <button style="" type="submit" onclick="return confirm('Are you sure?')" class='btn btn-danger btn-xs'>
                                    Delete
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            @endif
        </tbody>
    </table>
</div>
@endsection